# Statistics functions

In [3]:
# 1. Mean
# 2. median
# 3. mode
# 4. std(standard deviation)
# 5. var
# 6. max
# 7. min

## 1. np.mean()

In [2]:
import numpy as np
arr = np.random.randint(160, 180, size=20)
print(arr)

Mean = np.mean(arr)
print("Mean is : ",Mean)

[175 174 163 172 173 162 164 165 173 172 175 166 176 169 170 177 161 172
 171 164]
Mean is :  169.7


## 2. np.median()

In [15]:
# Median is the middle value from the array.
# If the length of an array is odd then median is the exact middle value present in the sorted array.
# If the length of an array is even then median is the mean of two middle values.
# for finding the Median first sort the array.

In [16]:
arr = np.array([30,23,50,76,55,79,66]) # odd length 
print("Array : ", arr)
sorted_arr = np.sort(arr)
print("Sorted Array : ", sorted_arr)
Median = np.median(sorted_arr)
print("Median is : ", Median)

Array :  [30 23 50 76 55 79 66]
Sorted Array :  [23 30 50 55 66 76 79]
Median is :  55.0


In [19]:
arr = np.array([30,23,50,76,80,55,79,66]) # even length
print("Array : ", arr)
sorted_arr = np.sort(arr)
print("Sorted Array : ", sorted_arr)
Median = np.median(sorted_arr)
print("Median is : ", Median) # (55+66)/2 i.e Median = mean of middle two element

Array :  [30 23 50 76 80 55 79 66]
Sorted Array :  [23 30 50 55 66 76 79 80]
Median is :  60.5


## 3. np.std() (standard Deviation)

In [20]:
# deviation means the scatterdness(distribution) around the central tendency(mean)

In [23]:
arr = np.array([5,4,1,8,9,3])
np.mean(arr)

np.float64(5.0)

In [24]:
np.std(arr)

np.float64(2.7688746209726918)

In [3]:
arr = np.random.randint(10, 50, size = 20)
print("Array is : ",arr)
mean = np.mean(arr)
print("Mean : ", mean)
Standard_Deviation = np.std(arr)
print("Standard Deviation is : ",Standard_Deviation)

Array is :  [38 37 30 17 39 16 16 32 34 42 34 14 46 21 45 34 26 25 37 21]
Mean :  30.2
Standard Deviation is :  9.846826900072937


In [4]:
arr = np.random.randint(10, 30, size = 10)
print("Array is : ",arr)
mean = np.mean(arr)
print("Mean : ", mean)
Standard_Deviation = np.std(arr)
print("Standard Deviation is : ",Standard_Deviation)

Array is :  [26 18 11 17 28 10 10 24 22 23]
Mean :  18.9
Standard Deviation is :  6.410148204214939


In [5]:
18.9 + 6.41  # positive standard deviation

25.31

In [6]:
18.9 - 6.41  # Negative standard deviation

12.489999999999998

In [7]:
# If we draw the curve of above array then we got the standard deviation about the mean value
# positive std ->> mean + std  (This is Maximun value Distributed around the mean)
# Negative std ->> mean - std  (This is Maximun value Distributed around the mean)

## 4. np.var() (Variance)

In [9]:
# Variance is the square of standard Deviation

In [10]:
arr = np.random.randint(10, 30, size = 10)
print("Array is : ",arr)
mean = np.mean(arr)
print("Mean : ", mean)
Standard_Deviation = np.std(arr)
print("Standard Deviation is : ",Standard_Deviation)
var = np.var(arr)
print("Variance is : ",var) # square of std

Array is :  [28 29 27 29 17 29 19 11 25 18]
Mean :  23.2
Standard Deviation is :  6.112282715974449
Variance is :  37.35999999999999


## 5. min()

In [ ]:
# We can find the minimum value by using :
# min(array)
# np.min(array)

In [22]:
arr = np.random.randint(10,20,size = 10)
arr

array([12, 14, 18, 13, 19, 17, 16, 18, 11, 17], dtype=int32)

In [23]:
print(min(arr))

11


In [25]:
print(np.min(arr))

11


## 6. max()

In [ ]:
# We can find the maximum value by using :
# max(array)
# np.max(array)

In [28]:
arr = np.random.randint(30,40, size = 20)
arr

array([35, 36, 31, 35, 30, 31, 39, 38, 30, 32, 35, 38, 34, 34, 32, 34, 30,
       37, 30, 37], dtype=int32)

In [29]:
max(arr)

np.int32(39)

In [30]:
np.max(arr)

np.int32(39)

## 7. mode()

In [31]:
# Mode is the most repeated values or the most occcured value in the array
# for findig mode we have to import mode from scipy library or we can also use dataframe (df) i.e df.mode()


In [7]:
arr = np.random.randint(40,60,size = 10)
arr

array([55, 54, 59, 46, 42, 56, 51, 52, 55, 43], dtype=int32)

In [8]:
from scipy.stats import mode
Mode = mode(arr)
print(Mode)
print(type(Mode))

ModeResult(mode=np.int32(55), count=np.int64(2))
<class 'scipy.stats._stats_py.ModeResult'>


In [9]:
Mode[0]  # It gives which value iss most repeated

np.int32(55)

In [55]:
Mode[1]  # It gives the how many times the value is repeated 

np.int64(2)

In [15]:
# by using dataframe

import pandas as pd
df = pd.DataFrame(arr)
print(df)
df.mode

    0
0  55
1  54
2  59
3  46
4  42
5  56
6  51
7  52
8  55
9  43


<bound method DataFrame.mode of     0
0  55
1  54
2  59
3  46
4  42
5  56
6  51
7  52
8  55
9  43>