# Numpy Functions

# 11. np.append()

In [5]:
import numpy as np

In [2]:
# append is used to append the element at the last of the array
# Syntax - np.append(array1,array2, axis)

# When axis = 0 ->> rows 
#      axis = 1 ->> columns
# Means when axis is 0 then values of second array is added as last rows and
# If the axis is 1 then values of second array are added as a columns

In [4]:
# In Python 
# In python array is added as a nested array 
arr1 = [1,2,3,4]
arr2 = [5,6,7,8]
arr1.append(arr2)
arr1

[1, 2, 3, 4, [5, 6, 7, 8]]

In [7]:
# By Using Numpy
# It adds the array element and make it as single array

arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])
np.append(arr, arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr = np.array([1,32,4,56])
np.append(arr, 1000)

array([   1,   32,    4,   56, 1000])

In [6]:
# It adds only one value at a time i.e 2000 will not be appended

arr = np.array([1,32,4,56])
np.append(arr, 3000)
# np.append(arr, 1000, 2000)

array([   1,   32,    4,   56, 3000])

In [17]:
# for 2-D array (use of axis)

# For axis = 0 , Second array will be appended as a rows

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[10,11,12,13],[14,15,16,17]])

print("array1 is: \n", arr1)
print("array2 is: \n", arr2)

np.append(arr1, arr2, axis = 0)

array1 is: 
 [[1 2 3 4]
 [5 6 7 8]]
array2 is: 
 [[10 11 12 13]
 [14 15 16 17]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [7]:
# For axis = 1 , Second array will be appended as a column elements

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[10,11,12,13],[14,15,16,17]])

print("array1 is: \n", arr1)
print("array2 is: \n", arr2)

np.append(arr1, arr2, axis = 1)

array1 is: 
 [[1 2 3 4]
 [5 6 7 8]]
array2 is: 
 [[10 11 12 13]
 [14 15 16 17]]


array([[ 1,  2,  3,  4, 10, 11, 12, 13],
       [ 5,  6,  7,  8, 14, 15, 16, 17]])

In [18]:
# It flattens the array means the multidimensional array is converted into 1-D arrat

arr1 = np.array([[1,2],[3,4]])  # 2-D
arr2 = np.array([[5,6],[7,8]])  # 2-D
arr = np.append(arr1,arr2)  # flatten the array
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

# 12. np.sort()

In [19]:
arr1 = np.random.randint(10,50, size = 10)
arr1

array([26, 42, 47, 43, 26, 20, 15, 31, 24, 47], dtype=int32)

In [20]:
sorted_array = np.sort(arr1)
sorted_array

array([15, 20, 24, 26, 26, 31, 42, 43, 47, 47], dtype=int32)

In [21]:
# 2-D
arr = np.array([[29,2],[37,23]])
arr1 = np.sort(arr)
arr1

array([[ 2, 29],
       [23, 37]])

# 13. np.concatenate()

In [22]:
# np.concatenate([arr1,arr2,arr3,....])
# It is Used to concatenate multiple arrays


In [25]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,9])
arr3 = np.array([37,48,29,93])
np.concatenate([arr1,arr2,arr3])

array([ 1,  2,  3,  4,  5,  6,  7,  9, 37, 48, 29, 93])

In [29]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[10,11,12,13],[14,15,16,17],[85,94,39,39]])
arr3 = np.concatenate([arr1,arr2])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [85, 94, 39, 39]])

In [30]:
# We can also concatenate values at the columns by using axis = 1, because by default axis = 0 i.e values added at the row
# for using axis the all lists should be of same shape

In [32]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[10,11,12,13],[14,15,16,17]])
arr3 = np.concatenate([arr1,arr2], axis = 1)
arr3

array([[ 1,  2,  3,  4, 10, 11, 12, 13],
       [ 5,  6,  7,  8, 14, 15, 16, 17]])