In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [21]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
arr6=np.arange(1,20,2)
arr6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
arr7=np.linspace(0,9,4)
arr7

array([0., 3., 6., 9.])

In [6]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9], dtype=str)
print(arr1)
print(arr1.ndim)

['1' '2' '3' '4' '5' '6' '7' '8' '9']
1


In [1]:
import numpy as np

In [8]:
arr1= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [13]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
arr


[[1 2]
 [3 4]
 [5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
print(np.shape(arr))

(2, 6)
