# Numpy - Functions

In [5]:
import numpy as np

In [1]:
list1 = [2,3,4,5,7,8]
list1.index(5)

3

# np.where(condition)

In [3]:
# np.where(condition)
## It returns the indices of particular value from dataframe based on condition
# It will traverse through the array and check the condition

In [9]:
arr = np.array([3,4,56,6,3,42,742,434,65,34])
print("Array is : ",arr)
indices = np.where(arr > 20) # It will returns the indices of the values those are greater than 20
print("Indices : ",indices)
print("List of Indices : ",indices[0])

Array is :  [  3   4  56   6   3  42 742 434  65  34]
Indices :  (array([2, 5, 6, 7, 8, 9]),)
List of Indices :  [2 5 6 7 8 9]


In [23]:
arr = np.array([3,4,56,6,3,42,742,434,65,34])
print("Array is : ",arr)
indices = np.where(arr >= 65)
list1 = list(indices)
print(list1[0])

Array is :  [  3   4  56   6   3  42 742 434  65  34]
[6 7 8]


In [36]:
arr = np.array([3,4,56,6,3,42,742,434,65,34])
print("Array is : ",arr)
indices = np.where((arr >= 20) & (arr <= 65))
print("Indices : ",indices[0])

Array is :  [  3   4  56   6   3  42 742 434  65  34]
Indices :  [2 5 8 9]


In [43]:
arr = np.array([3,4,5,6,10,20,30,40,1,2,3,7,8,9])
print(arr)
indices = np.where((arr <= 10) & (arr % 2 == 0)) # It returns the indices of the values which are less than 10 and are even i.e follows both the condition

print("Indices : ",indices[0])

arr[indices[0]] # It will return the actual values from the array that satisfies the conditions

[ 3  4  5  6 10 20 30 40  1  2  3  7  8  9]
Indices :  [ 1  3  4  9 12]


array([ 4,  6, 10,  2,  8])

# np.sqrt()

In [47]:
np.sqrt(4)

np.float64(2.0)

In [49]:
arr = ([4,8,16,64])
sqroot = np.sqrt(arr)
print(sqroot)

[2.         2.82842712 4.         8.        ]


# np.cbrt()

In [54]:
np.cbrt(8)

np.float64(2.0)

In [52]:
arr = ([4,8,16,64])
cuberoot = np.cbrt(arr)
print(cuberoot)

[1.58740105 2.         2.5198421  4.        ]


# np.full()

In [55]:
# np.full(number of value, values that will printed)

In [56]:
np.full(20, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
np.full(20, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [58]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.copy()

In [66]:
# When we copy like below then changes made in any one array is get reflected in both the array
# Thus we have to use np.copy() function

arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = arr1
print(arr1)
print(arr2)

arr2[1] = 1000
print(arr1) # the change made in arr2 is also get reflected in arr1
print(arr2)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[   1 1000    3    4    5    6    7    8    9]
[   1 1000    3    4    5    6    7    8    9]


In [78]:
# np.copy()

arr1 = np.array([10,20,34,48,53,66,72,80,97])
arr2 = np.copy(arr1)

print(arr1)
print(arr2)

arr2[1] = 6000

print(arr1) # It will remain same as before changees made in arr2
print(arr2)

[10 20 34 48 53 66 72 80 97]
[10 20 34 48 53 66 72 80 97]
[10 20 34 48 53 66 72 80 97]
[  10 6000   34   48   53   66   72   80   97]


In [76]:
arr1 = np.array([[10,20],[80,97]])
arr2 = np.copy(arr1)

print("Array 1 : ",arr1)
print("Array 2 : ",arr2)

arr2[1, 0] = 6000

print(arr1)
print(arr2)

Array 1 :  [[10 20]
 [80 97]]
Array 2 :  [[10 20]
 [80 97]]
[[10 20]
 [80 97]]
[[  10   20]
 [6000   97]]
