# Numpy - Linear Algebra

In [1]:
import numpy as np

In [2]:
2x + 5y = 15
3x + 4y = 20

x = ?
y = ?

SyntaxError: invalid decimal literal (516093367.py, line 1)

In [6]:
arr_A = np.array([[2,5],[3,4]])
arr_B = np.array([15, 20])

print("Array A is : \n", arr_A)
print("Array B is : \n", arr_B)

result = np.linalg.solve(arr_A,arr_B)
print("Result : ",result)

Array A is : 
 [[2 5]
 [3 4]]
Array B is : 
 [15 20]
Result :  [5.71428571 0.71428571]


In [ ]:
3x + 5y + 6z = 30
4x + 7y + 8z = 20
4x + y + 9z = 43

x = ?
y = ?
z = ?

In [9]:
arr_A = np.array([[3,5,6],[4,7,8],[4,1,9]])
arr_B = np.array([30,20,43])

print("Array A is : \n", arr_A)
print("Array B is : \n", arr_B)

Result = np.linalg.solve(arr_A, arr_B)
print("Result : ", Result)

Array A is : 
 [[3 5 6]
 [4 7 8]
 [4 1 9]]
Array B is : 
 [30 20 43]
Result :  [ 784.  -60. -337.]


# Inverse of Matrix

In [10]:
arr = np.array([[3,4],[5,6]])
arr

array([[3, 4],
       [5, 6]])

In [13]:
arr1 = np.linalg.inv(arr)
arr1

array([[-3. ,  2. ],
       [ 2.5, -1.5]])