In [9]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
d = np.random.randint(1,100, 50)

In [11]:
d1 = np.random.randint(1,100, 50)

In [12]:
d1

array([72, 14, 36, 44, 15, 55, 83, 61, 76, 96, 54, 77, 12, 92, 81, 82, 26,
       43, 75, 50, 99, 10, 98, 50, 71, 44, 27, 73, 36,  8, 64, 84, 49,  1,
       74, 25, 16, 74, 67, 40, 62, 91, 43, 46, 67, 41, 30, 77, 57, 18],
      dtype=int32)

In [13]:
d

array([22, 58, 87, 42, 26, 71, 37, 94, 13,  6, 12, 33, 74, 64, 70,  9, 34,
       21, 54, 41, 25, 56, 28, 12, 12, 62, 25, 13, 32, 58, 86, 38, 51, 95,
       35, 10, 99, 90,  2, 98, 46, 23, 30, 83,  3,  4, 16, 81, 24, 79],
      dtype=int32)

In [46]:
data = {
'Age':[22, 58, None, 42, None, 71, 37, 94, 
       13,  6, 12, 33, 74, 64, 70,  9, 34,
       21, 54, 41, 25, 56, None, 12, 12, 62, 25, 13, 32, 58, 86, 38, 51, 95,
       35, 10, 99, 90,  2, 98, 46, 23, 30, 83,  3,  4, 16, 81, 24, 79],
'Value':[72, 14, 36, 44, 15, 55, 83, 61, 76, 96, 54, 77, 12, 92, 81, 82, 26,
       43, 75, 50, 99, 10, 98, 50, 71, 44, 27, 73, 36,  8, 64, 84, 49,  1,
       74, 25, 16, 74, 67, 40, 62, 91, 43, 46, 67, 41, 30, 77, 57, 18]
}

In [47]:
df  = pd.DataFrame(data)

In [48]:
df.head()

,Age,Value
0,22.0,72
1,58.0,14
2,NaN,36
3,42.0,44
4,NaN,15


In [20]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [49]:
X = df.drop("Value", axis =1)
Y = df.drop('Age', axis=1)

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X , Y, test_size = 0.2,random_state =22)

In [71]:
X_train

,Age
35,10.0
41,23.0
16,34.0
49,79.0
13,64.0
23,12.0
11,33.0
9,6.0
10,12.0
37,90.0


In [73]:
X_test

,Age
32,51.0
12,74.0
25,62.0
47,81.0
33,95.0
22,NaN
3,42.0
30,86.0
26,25.0
1,58.0


In [ ]:
imputer1 = SimpleImputer(strategy = 'median')
# imputer2 = SimpleImputer(strategy='mean')

X_train = imputer1.fit_transform(X_train)
X_test = imputer1.fit_transform(X_test)

In [75]:
X_train

array([[10. ],
       [23. ],
       [34. ],
       [79. ],
       [64. ],
       [12. ],
       [33. ],
       [ 6. ],
       [12. ],
       [90. ],
       [56. ],
       [94. ],
       [32. ],
       [46. ],
       [41. ],
       [37. ],
       [21. ],
       [ 4. ],
       [32.5],
       [24. ],
       [13. ],
       [ 9. ],
       [71. ],
       [30. ],
       [35. ],
       [98. ],
       [12. ],
       [70. ],
       [54. ],
       [58. ],
       [16. ],
       [38. ],
       [13. ],
       [25. ],
       [83. ],
       [ 2. ],
       [99. ],
       [22. ],
       [ 3. ],
       [32.5]])

In [76]:
X_test

array([[51.],
       [74.],
       [62.],
       [81.],
       [95.],
       [62.],
       [42.],
       [86.],
       [25.],
       [58.]])